Added keypoint matplotlib viewer
DeepLabCut/napari-DeepLabCut pull request #90
Opened 2023-08-25 15:26 UTC by hausmanns

Matplotliib viewer to view your keypoints' trajectory synced with the video and keypoints.

Activate plugin, upload your .h5 (and video, not necessary), and tick "show matplotlib trajectory"

For now it's still hardcoded to the naming of my keypoints of interests.
Needs to be adapted to keypoints from the GUI directly, in here:

![image](https://github.com/DeepLabCut/napari-deeplabcut/assets/37653619/3e683291-6d6b-4757-a1eb-5925237da8e8)

https://github.com/DeepLabCut/napari-deeplabcut/assets/37653619/2cc70a56-f8ef-4c0c-a252-d133054e6193

2023-08-31 08:00 UTC, jeylau commented
https://github.com/DeepLabCut/napari-deeplabcut/assets/30733203/ae3699c3-f08a-41f2-9c8f-d4fb6623fee1

2023-08-31 08:03 UTC, jeylau commented
Probably a couple of tweaks that could be made here and there; but that works very smoothly even for maDLC.

2023-08-31 13:17 UTC, hausmanns commented
Another thing that should be tweaked @jeylau :

They y_lim should be independent of the dataset and dependent on the plot window (or adjustable)
Indeed, keypoint jumps can squeeze the window depending on the dataset's quality

2023-08-31 13:21 UTC, jeylau commented
Good point; one thing that could be added then is a `NavigationToolbar2QT`, which would allow pan, zoom, etc.

2023-09-14 12:45 UTC, MMathisLab commented
Is this superceded by #92 ?

2023-09-14 13:51 UTC, jeylau commented
@MMathisLab, these 2 PRs are distinct components. I will add the toolbar Seb mentioned above so this one is reader 😊

2023-09-14 14:20 UTC, jeylau commented
Also, regarding the warnings in the console, they will be removed with napari's next release and vispy >= 0.13 https://github.com/napari/napari/pull/6025

2023-09-14 16:56 UTC, MMathisLab commented
I think we need to address failing tests here before merge, right?

2023-09-14 17:35 UTC, jeylau commented
Mhhh, napari removed the plugin preview service https://github.com/chanzuckerberg/napari-hub/discussions/1216. I'll delete the github action.

2023-09-15 13:14 UTC, MMathisLab commented
so, ready to merge?

2023-09-15 13:19 UTC, jeylau commented
Yes, looking good to me!

2023-09-15 14:06 UTC, MMathisLab commented
can you review it then, so we can merge?

2023-09-15 14:31 UTC, MMathisLab requested changes

2023-09-15 14:31 UTC, MMathisLab commented on setup.cfg
> +    matplotlib
isn't this installed with DLC proper, and we should be mindful of version?

2023-09-15 16:14 UTC, MMathisLab approved these changes

2023-09-15 17:45 UTC, merged